export const tripData = {
  title: "03/2024",
  details: [
    {
      title: "Czechy",
      mapImage: "",
      parts: [
        {
          title: "Zamek hurkvaldy",
          details: `
          <img src="https://www.beskydyportal.cz/photos/top10/hrad-hukvaldy-7-9871.jpg">
          <p class="p1">Zamek Hukvaldy, to jeden z&nbsp;największych kompleks&oacute;w zamkowych w Czechach, od XIX wieku cel częstych wycieczek turystycznych.</p>
          <p class="p1">Nazwa Hukvaldy pochodzi od książąt H&uuml;ckeswagen, kt&oacute;rego członek Arnold otrzymał w latach 1228&ndash;1235 rozległe terytorium w okolicy zamku Jič&iacute;n (dzisiejszy Star&yacute; Jič&iacute;n). Zamek Hukvaldy zbudował prawdopodobnie dopiero jego wnuk Jindřich. P&oacute;źniej się właścicielem zamku stal biskup ołomuniecki.</p>
          <p class="p1">Zamek Hukvaldy nie był tylko fortyfikacją, był r&oacute;wnież siedzibą administracyjną domeny. Najpierw rodu H&uuml;ckeswagen, p&oacute;źniej biskup&oacute;w ołomunieckich. W 1760 roku była administracja domeny przeniesiona z&nbsp;zamku (Starego zamku) do kamienicy (Nowego zamku) w wiosce Hukvaldy. To był początek końca zamku Hukvaldy, kt&oacute;ry się stal przede wszystkim tanim źr&oacute;dłem kamienia budowlanego dla mieszkańc&oacute;w wioski Hukvaldy. Z zamku zostały tylko ruiny.</p>
          <p class="p1">&bdquo;Nowe życie&rdquo; zamku rozpoczęło się w XIX wieku we związku z&nbsp;turystyką, duże zainteresowanie ludzi zamkiem doprowadziło do jego zachowania dla przyszłych pokoleń i&nbsp;wykorzystania go jako centrum wydarzeń kulturalnych.&nbsp;</p>
          <p class="p1">&nbsp;</p>
          `,
        },
        {
          title: "Hradec nad Moravicí - Grodziec Golęszycki",
          details: `
          <img class="left" src="https://www.tourism-pl-cz.eu/gallery/attraction/image_5cbc45bf70256.jpg" />
          <p class="p1">Kompleks pałacowo-parkowy w Hradcu nad Moravic&iacute; (pol. Grodziec Golęszycki) znajduje się na p&oacute;łnocno-wschodnim cyplu Niskiego Jesionika u ujścia potoku Hradečn&aacute; do rzeki Moravicy. Pierwsze wzmianki o grodzie i zamku pochodzą z poł. XI w. Po pożarze w poł. XIII w. kr&oacute;l Przemysł Otokar II (około 1233 &ndash; 1278) zbudował tu gotycki zamek. Ten z czasem przebudowano w stylu renesansowym, a następnie barokowym. <br />Aktualny wygląd rezydencja zawdzięcza ostatniej przebudowie w stylu empire. Biały Pałac wraz z potężną pseudogotycką Białą Wieżą i Czerwonym Zamkiem otacza rozległy park w stylu angielskim.</p>
          `,
        },
        {
          title: "Ogrody Opava",
          details: `<img src="https://www.podrozepokulturze.pl/wp-content/uploads/2018/05/opawa-zwiedzanie-16-1024x614.jpg" alt=""/>
          <p class="p1">Bardzo blisko Opavy, w miejscowości Nov&yacute; Dvůr, znajduje się jeden z ładniejszych ogrod&oacute;w botanicznych w Czechach poświęcony przede wszystkim dendrologii, czyli roślinom drzewiastym. Założony na początku XX wieku przez Quido Riedela na niewielkiej powierzchni 1,8 ha, ten kolorowy ogr&oacute;d botaniczny zachwyca obecnie kilkoma tysiącami gatunkami drzew i krzew&oacute;w na obszarze o powierzchni 30 hektar&oacute;w.</p>`,
        },
        {
          title: "Zamek Helfštýn",
          details: `<img class="left" src="https://www.ok-tourism.cz/data/images/fotografie/fd/hrad-helfstyn06.jpg" alt=""/>
          <p class="p1">Zamek został założony pod koniec&nbsp;<span class="s1">XIII</span>&nbsp;wieku przez&nbsp;<span class="s2">Bedřicha z Linavy</span>. W następnych wiekach należał do majątku kilku szlacheckich rod&oacute;w, przede wszystkim&nbsp;<span class="s1">morawskich</span>. Po&nbsp;<span class="s1">bitwie na Białej G&oacute;rze</span>&nbsp;został skonfiskowany i przypadł w udziale kardynałowi&nbsp;<span class="s1">Franzowi von Dietrichsteinowi</span>. Aż do roku&nbsp;<span class="s1">1656</span>&nbsp;zamek służył jako wojskowa fortyfikacja, p&oacute;źniej posterunek wojskowy zlikwidowano, a arsenał przewieziono do&nbsp;<span class="s1">Ołomuńca</span>. Od&nbsp;<span class="s1">XVII</span>&nbsp;wieku porzucony zamek powoli popadał w ruinę.</p>
<p class="p1">Rozległy kompleks ruin jest obecnie stopniowo rekonstruowany, odbywa się tu też szereg wydarzeń kulturalnych - do najważniajszych zalicza się wystawa dzieł&nbsp;<span class="s1">kowalstwa</span>&nbsp;artystycznego&nbsp;<em>Hefaiston</em>.</p>`,
        },
        {
          title: "Bouzov - czeski zamek jak z bajki",
          details: `<img src="https://i0.wp.com/wdrodze.tv/wp-content/uploads/2024/01/dji_fly_20230909_115630_270_1694257327559_photo-scaled.jpg" alt=""/>
          <p data-reactid="178">Na Morawach, mniej znanej Polakom południowo-wschodniej części Czech, znajduje się wiele skarb&oacute;w architektury. Jednym z nich jest średniowieczny zamek Bouzov. W przeciwieństwie do innych tego typu budowli w regionie, ta nigdy nie opustoszała. Poznajcie burzliwe dzieje obiektu nazywanego często czeskim Neuschwansteinem.</p>
</div>
<div class="article--text hFQN8OU2 hYwaUr3X" data-reactid="179">
<p>Zamek&nbsp;Bouzov, wyrastający na wzg&oacute;rzu pośr&oacute;d las&oacute;w, znajdziemy ok. 30 km na p&oacute;łnocny wsch&oacute;d od Ołomuńca. Powstał na przełomie XIII i XIV wieku, kiedy to podczas intensywnej kolonizacji&nbsp;<strong>Moraw</strong>, ludzie osiedlali się wzdłuż szlak&oacute;w handlowych wiodących do Czech. Budowano w&oacute;wczas m.in. warownie - jedną z nich był Bouzov, kt&oacute;ry stanął przy trasie kupc&oacute;w wiodącej z Ołomuńca przez Litomyśl do Pragi. Przez ponad trzy stulecia, aż do roku 1696, często przechodził z rąk do rąk i kilka razy był rozbudowywany.</p>
`,
        },
        {
          title: "Zamek Český Šternberk",
          details: `<img class="left" src="https://www.justride.cz/Content/Images/TripTip/hrad-cesky-sternberk/583322b14fad41a1834f41b989da1cad.jpg" alt=""/>
          <p data-reactid="178">Zamek pierwotnie w stylu wczesnogotyckim, w&nbsp;<strong>XVI wieku</strong>&nbsp;całkowicie przebudowany w stylu p&oacute;źnego gotyku. Obecny wygląd zyskał w II połowie&nbsp;<strong>XVIII wieku</strong>. Zamek został zbudowany w&nbsp;<strong>1241 roku</strong>&nbsp;przez&nbsp;<strong><em>Zdeslava z Divi&scaron;ovec</em></strong>, kt&oacute;rego &oacute;wcześni nazwali&nbsp;<strong><em>"&Scaron;ternberkiem"</em></strong>. Od tamtego czasu datuje się nową nazwę rodu&nbsp;<strong><em>&Scaron;ternberk&oacute;w</em></strong>, pochodzącą od herbu z ośmioramienną gwiazdą&nbsp;<strong>(<em>Stern - niem.&nbsp;</em></strong><strong><em>gwiazda</em>&nbsp;</strong>oraz<strong>&nbsp;<em>Berg - niem.&nbsp;</em></strong><strong><em>brzeg</em>)</strong>. W&nbsp;<strong>XIV wieku</strong>&nbsp;rozbudowano system obronny zamku poprzez budowę trzypiętrowej wieży połączonej z zamkiem potężnym murem obronnym. W&nbsp;<strong>1467 roku</strong>&nbsp;zamek został zdobyty przez wojska kr&oacute;lewskie&nbsp;<strong><em>Jiř&iacute;ka z Poděbrad</em></strong>. W&nbsp;<strong>1479 roku</strong>&nbsp;kr&oacute;l&nbsp;<strong><em>Władysław Jagiellończyk</em></strong>&nbsp;zwr&oacute;cił zamek wraz z posiadłościami rodowi&nbsp;<strong><em>&Scaron;ternberk&oacute;w</em></strong>. Na przełomie&nbsp;<strong>XV i XVI wieku</strong>&nbsp;uszkodzony zamek został naprawiony i rozbudowany. Ulepszono system obronny, w tym zbudowano cylindryczną wieżę południową zwaną&nbsp;<strong>"<em>hladomorna</em>"</strong>&nbsp;<strong>(loch)</strong>. W&nbsp;<strong>1627 roku</strong>&nbsp;zamek został splądrowany przez zbuntowanych obywateli pobliskich miejscowości. W&nbsp;<strong>latach 60-tych XVII wieku</strong>&nbsp;na zamku pracował znany włoski mistrz sztukaterski&nbsp;<strong><em>Carlo Brentano</em></strong>. W&nbsp;<strong>1712 roku</strong>&nbsp;bezpotomnie umiera&nbsp;<strong><em>Jan V&aacute;clav &Scaron;ternberk</em></strong>&nbsp;kończąc&nbsp;<strong><em>Holicką</em></strong>&nbsp;odnogę rodu&nbsp;<strong><em>&Scaron;ternberk&oacute;w</em></strong>. Zamek kolejno przechodzi w ręce r&oacute;żnych rod&oacute;w. W&nbsp;<strong>1751 roku</strong>&nbsp;zbudowano dolny zamek. W&nbsp;<strong>1841 roku</strong>&nbsp;zamek zostaje odkupiony przez&nbsp;<strong><em>Zdenka ze&nbsp;</em></strong><strong><em>Sternberga</em></strong>, przedstawiciela&nbsp;<strong><em>Konopi&scaron;ťskiej</em></strong>&nbsp;linii rodu&nbsp;<strong><em>&Scaron;ternberk&oacute;w</em></strong>. W&nbsp;<strong>1949 roku</strong>&nbsp;zamek został upaństwowiony, a jego właściciele wywłaszczeni. W&nbsp;<strong>1992 roku</strong>&nbsp;zamek zwr&oacute;cono prawowitemu właścicielowi -&nbsp;<strong><em>Zdenkowi&nbsp;</em></strong><strong><em>Sternbergovi</em></strong>.<br /><br /></p>
<p><span class="fs14 cf1"><strong>Trasa zwiedzania.</strong></span></p>
<blockquote>
<p><span class="fs11">Wnętrza zamku otwarte są dla zwiedzających i urządzone w stylu barokowym. Trasa zwiedzania prowadzi przez 15 bogato wyposażonych pokoi. Kolejno przechodzimy przez:<br /></span></p>
</blockquote>
<blockquote>
<blockquote>
<p><span class="fs11">- dużą, pięknie urządzoną&nbsp;<strong>salę rycerską (<em>ryt&iacute;řsk&yacute; s&aacute;l</em>)</strong>&nbsp;z wieloma cennymi zbiorami,<br />- pięknie zdobioną&nbsp;<strong>kaplicę&nbsp;</strong><strong>św.&nbsp;<em>&Scaron;ebesti&aacute;na</em></strong>,<br />-&nbsp;<strong>ż&oacute;łty salon (<em>žlut&yacute; sal&oacute;n</em>)</strong>&nbsp;z wczesnobarokową sztukaterią w stylu Ludwika XVI,<br />- przytulną&nbsp;<strong>bibliotekę (<em>knihovna</em>)</strong>&nbsp;z kilku tysiącami tom&oacute;w ksiąg i doskonałym obrazem, kt&oacute;ry jest przypisany&nbsp;<strong><em>Peterowi Brandlowi</em></strong>,<br />- dużą&nbsp;<strong>jadalnię (<em>j&iacute;delna</em>)</strong>&nbsp;zdobioną srebrnymi arkuszami, kt&oacute;rej ściany zdobi piękna kolekcja portret&oacute;w członk&oacute;w rodziny&nbsp;<strong><em>&Scaron;ternberk&oacute;w</em></strong>,<br />-&nbsp;<strong>orientalny hall</strong>&nbsp;i&nbsp;<strong>salę śniadaniową</strong>&nbsp;<strong>(<em>orient&aacute;ln&iacute; předs&iacute;ň</em>,&nbsp;<em>sn&iacute;daňov&yacute; pokoj</em>)</strong>&nbsp;z kolekcją srebrnych figurek oraz wyposażonych w kwieciście zdobione meble,<br />-&nbsp;<strong>gabinet (<em>pracovna</em>)&nbsp;<em>Jiř&iacute;ho &Scaron;ternberka</em></strong>, w kt&oacute;rym znajduje się drzewo genealogiczne rodu&nbsp;<strong><em>&Scaron;ternberk&oacute;w</em></strong>&nbsp;z ponad 63 portretami przodk&oacute;w w historycznych kostiumach i mundurach,<br />- cztery kolejne pokoje, w kt&oacute;rych możemy posmakować kolejno: rokoka, biedermeieru, empiru i baroku,<br />-&nbsp;<strong>salon myśliwski (<em>loveck&yacute; salon</em>)</strong>, kt&oacute;rego ściany ozdobione są r&oacute;żnymi trofeami zwierzęcymi,<br />-&nbsp;<strong>schody wejściowe (<em>vstupn&iacute; schodi&scaron;tě</em>)</strong>, kt&oacute;re zamykają trasę zwiedzania, a gdzie możemy podziwiać obrazy pędzla&nbsp;<strong><em>Filipa &Scaron;ternberka</em></strong>, przedstawiające sceny batalistyczne z XVIII, XIX i XX wieku.<br /></span></p>
</blockquote>
</blockquote>
<blockquote>
<p><span class="fs11">Na zamku możemy podziwiać wspaniałą kolekcję grafik, miedzioryt&oacute;w o tematyce wojny trzydziestoletniej, tzw. srebra holenderskie czyli miniatury z XVII wieku, kt&oacute;rą stworzył na początku XX wieku&nbsp;<strong><em>Jiř&iacute; &Scaron;ternberk</em></strong>. Kolekcja liczy 545 dzieł i stanowi jedną z najbardziej znanych tego typu kolekcji.&nbsp;Ekspozycje w salonach wzbogacone są kolekcjami historycznej broni, rzadkiej porcelany i r&oacute;żnymi przykładami drobnych wyrob&oacute;w rzemieślniczych minionych wiek&oacute;w.</span></p>
</blockquote>`,
        },
        {
          title: "Zamek Sovinec – miejsce o wielu obliczach",
          details: `<img src="https://cms.visitczechia.com/cms/getmedia/d1eaf27d-a5d3-4993-a8e4-633b857521ca/hrad-sovinec_041.jpg?width=1920&height=1279&ext=.jpg" alt=""/>
          <p data-reactid="178">Na występie skalnym wśr&oacute;d malowniczych wzg&oacute;rz Niskiego Jesionika ( N&iacute;zk&yacute; Jesen&iacute;k) wznosi się dumnie zamek Sovinec, kt&oacute;ry na przestrzeni stuleci był areną pełnej sprzeczności czeskiej historii. Powstała o sto lat wcześniej budowla stała się w XV wieku ważną husycką warownią. Po raz kolejny zamek znalazł się w niebezpieczeństwie podczas wojny trzydziestoletniej, kiedy to nawet potężne obwarowania nie zatrzymały ataku wojsk szwedzkich pod dow&oacute;dztwem generała Torstensona. Mimo tego dziś Sovinec może pochwalić się najlepiej zachowanymi w Czechach obwarowaniami z okresu wojny trzydziestoletniej. W czasie II wojnie światowej w zamku stacjonował oddział SS, część pomieszczeń zaadaptowano na więzienie. Z kolei w okresie normalizacji Sovinec stał się jedną z &bdquo;ostoi wolności&rdquo;, w kt&oacute;rej wystawiano dzieła zakazanych czeskich artyst&oacute;w.</p>`,
        },
        {
          title: "Vranov nad Dyjí",
          details: `<img class="left" src="https://www.zamek-vranov.cz/pamatky/vranov-nad-dyji/fotogalerie/o-zamku/historie/neprehlednete-/image-thumb__17459__SightHpTile/predhradi-pred-bourkou.webp" alt=""/>
          <p>Pałac leży na południowej granicy Czech, ok. 110 km od Wiednia i należy do najbardziej wartościowych budowli świeckich środkowoeuropejskiego baroku. Powstał w wyniku przebudowy zamku szlacheckiego, kt&oacute;rego pierwsze wzmianki datowane są na rok 1100.&nbsp;Wsp&oacute;łczesny wygląd w dużej mierze zawdzięcza austriackiemu architektowi Johannowi Bernhardowi Fischerowi von Erlach, kt&oacute;ry dokonał przebudowy w czasie, kiedy Vranov był własnością rodu Althann&oacute;w (od schyłku XVII wieku przez ponad sto lat). Po nich właścicielami zostali polscy Mniszkowie, kt&oacute;rzy doprowadzili do niebywałego rozkwitu słynną vranovską manufakturę produkującą kamionkę i porcelanę.</p>
    <p>Pałac znajduje się w zachodniej części Parku Narodowego Podyj&iacute; i stanowi część dziedzictwa narodowego. Turystom oferuje zwiedzanie autentycznych pomieszczeń barokowych - Sali Przodk&oacute;w i kaplicy, ale obrazuje także kulturę mieszkania w pałacu vranovskim pod koniec XVIII i w XIX wieku.</p>`,
        },
        {
          title: "Zamek Špilberk",
          details: `<img src="https://zamkiobronne.pl/wp-content/uploads/2020/10/brno_2019_03.jpg" alt=""/>
          <p class="p1">Znane w całej Europie, osnute wieloma mrożącymi krew w żyłach legendami straszliwe więzienie, cenne zbiory historyczne, piękny widok na miasto i obfitość imprez kulturalnych odbywających się przez cały rok &ndash; to właśnie zamek &Scaron;pilberk. Budowla ta jest znakiem rozpoznawczym Brna, a zarazem jednym z najcenniejszych zabytk&oacute;w w morawskiej metropolii.</p>
    <p class="p1">Na przestrzeni stuleci znaczenie i&nbsp;rola obiektu uległy istotnym zmianom. Ze wspaniałego kr&oacute;lewskiego zamku oraz siedziby morawskich margrabi&oacute;w stopniowo powstawały: potężna barokowa twierdza, najsurowsze więzienie monarchii austriackiej, i&nbsp;wreszcie koszary wojskowe. Dziś budowla mieści Muzeum Miasta ( Muzeum města) Brna oraz jedno z&nbsp;najważniejszych brneńskich centr&oacute;w kultury.</p>`,
        },
        {
          title: "Křivoklát",
          details: `<img class="left" src="https://www.hrad-krivoklat.cz/pamatky/krivoklat/fotogalerie/Karusel/image-thumb__94719__OgTagImage/00_web_karusel_Krivoklat.webp" alt=""/>
          <p class="p1">Pośr&oacute;d zalesionych wzg&oacute;rz jaśnieje bielą wysoka cylindryczna wieża starodawnego zamku z potężnymi umocnieniami. Ze względu na dogodne położenie w głębokich lasach pełnych zwierzyny, upodobali go sobie liczni czescy władcy. Sale zamku były świadkami hucznych uczt, przyjęć i pijatyk, jak r&oacute;wnież wielu ważnych rozm&oacute;w politycznych i brzemiennych w skutki decyzji dyplomatycznych.<br /><br />Zamek po wielu pożarach przeszedł kolejne rekonstrukcje, kt&oacute;re zakończyły się dopiero w XX wieku. Jedynym pomieszczeniem, w kt&oacute;rym zachowało się pierwotne wyposażenie, jest gotycka kaplica z bogato rzeźbionym ołtarzem. Ślady kr&oacute;l&oacute;w czeskich i przepych ich stylu życia widać tu jednak na każdym kroku. W przywracaniu wnętrzom dawnej świetności mają udział konserwatorzy zabytk&oacute;w, kt&oacute;rzy z&nbsp;powodzeniem sprowadzają na dawne miejsce odwiezione stąd kiedyś historyczne zbiory.<br /></p>`,
        },
        {
          title: "Zamek Pernštejn",
          details: `<img src="https://i.wpimg.pl/630x0/i.wp.pl/a/f/jpeg/32335/3/9/395af17ae718992eb2ecf1dde1b2eb7a.jpeg" alt=""/>
          <p class="p1">Głęboko w lasach Masywu Czeskomorawskiego (Českomoravsk&aacute; vrchovina) od przeszło ośmiu wiek&oacute;w wznosi się jeden z najpiękniejszych morawskich zamk&oacute;w. Warto zainteresować się dziejami tej wspaniałej siedziby rodu Pern&scaron;tejn&oacute;w, przejść się po jej komnatach i wspiąć na baśniową wieżę. Odważnym turystom być może uda się także spotkać tutejszą Białą Damę! Pern&scaron;tejn to nie tylko jeden z najważniejszych czeskich zabytk&oacute;w, ale także budowla, kt&oacute;ra ze względu na swą imponującą architekturę cieszy się niesłabnącym powodzeniem wśr&oacute;d filmowc&oacute;w z całego świata.<br />Wspaniałe gotyckie zamczysko powstało jako siedziba Pern&scaron;tejn&oacute;w, o&nbsp;kt&oacute;rych pochodzeniu do dziś niewiele wiadomo. Pewne jest, że należeli oni do najbogatszych czeskich rod&oacute;w, ich majątki w&nbsp;swoim czasie przewyższały włości sławnych Rožmberk&oacute;w z&nbsp;południa Czech. Schyłek rodu oraz stopniowe rozprzedawanie posiadłości przypieczętowały bezzwrotne pożyczki dla cesarzy.<br /><br /><strong>Niepokonany kr&oacute;l czeskich zamk&oacute;w</strong><br />Spoglądając na monumentalną sylwetkę zamku, trudno się dziwić, że na przestrzeni dziej&oacute;w nie został on nigdy zdobyty. Stało się tak dzięki pieczołowicie zaprojektowanemu systemowi obronnemu, kt&oacute;ry zadziwia do dziś. Strategiczna lokalizacja na wysokiej skale, głębokie fosy, mosty zwodzone i&nbsp;wysokie mury obronne z&nbsp;wieżami &ndash; na wypadek, gdyby i&nbsp;te elementy zabezpieczające okazały się niewystarczające, właściciele zamku mogli ukryć się w&nbsp;pięciopiętrowej wieży Barborka połączonej z&nbsp;pobliskimi zabudowaniami tylko dwoma drewnianymi mostami. Jeśli wr&oacute;g mimo tego dostałby się do wewnątrz, czekały tu na niego wąskie korytarze, przez kt&oacute;re rycerz w&nbsp;zbroi nie m&oacute;głby się przecisnąć.<br /><br /><strong>Pern&scaron;tejn &ndash; tylko dla odważnych</strong><br />Podobnie jak większość czeskich zamk&oacute;w, także Pern&scaron;tejn ma swego tajemniczego mieszkańca. Mowa o&nbsp;Białej Damie, kt&oacute;ra była niegdyś zamkową służącą. Zaniedbywała jednak ona swoje obowiązki i&nbsp;wciąż tylko mizdrzyła się do zwierciadła. Kiedy przestała chodzić także na msze, stary mnich uznał, że musi przem&oacute;wić jej do rozumu. Służąca wyśmiała jego starania, co tak go rozzłościło, że przeklął ją na wieki. Podobno do dziś zjawa dziewczyny błąka się po ciemnych zamkowych korytarzach. Turystki powinny podczas zwiedzania uważać na zamkowe lustra. Legenda m&oacute;wi, że kobieta, kt&oacute;ra w&nbsp;nie spojrzy, w&nbsp;ciągu roku utraci swą urodę.<br /><br /></p>`,
        },
        {
          title: "Niemożliwy do zdobycia zamek Rabí",
          details: `<img class="left" src="https://cdn.podroze.smcloud.net/t/image/t/133736/zamki-w-czechach-rabi_414690.jpg" alt=""/>
          <p class="p1">Pozostałości śnieżnobiałego zamku malowniczo odcinają się od przepięknego krajobrazu rozpościerającego się nad rzeką Otavą. Niegdyś zamek pełnił funkcję ochronną dla szlaku handlowego łączącego miasta Su&scaron;ice i Horažďovice oraz bogatych zł&oacute;ż złota nad rzeką Otavą, obecnie z niemal trzema kilometrami zachowanych mur&oacute;w jest uważany za największe czeskie ruiny zamkowe. Warto wspiąć się na donżon, wysoką wieżę obronną, z kt&oacute;rej roztacza się wspaniały widok na okolicę, lub obejrzeć wystawę cennych średniowiecznych dekorowanych kafli stanowiących unikat na skalę światową. Dodatkową ciekawostką dla os&oacute;b zainteresowanych historią będzie z pewnością fakt, że właśnie w tym miejscu Jan Žižka w czerwcu 1421 stracił drugie oko.</p>`,
        },

      ],
    },
  ],
};
